name = "sinlapa-preview"
pages_build_output_dir = "public"
compatibility_date = "2026-07-31"

[[kv_namespaces]]
binding = "SITE_CONFIG"
id = "d9e0ba7c99c54d95a3e75b14ff502297"
preview_id = "d9e0ba7c99c54d95a3e75b14ff502297"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "sinlapa-media"
preview_bucket_name = "sinlapa-media-preview"
